# Matrices in numpy

We explored matrices in MATLAB last year, but didn't do this in python ... This was because you hadn't covered matrices in the math modules by that point, so let's do this now.

## Transposing and reshaping arrays

Let's move on now to consider some multi-dimension arrays. Let's first consider the following 5 x 5 array of random numbers uniformly distributed between 0 and 10:

In [2]:
import numpy as np

nums = np.random.random_sample(size=[12,10]) * 10
print (nums)

[[6.43025026 2.86475989 2.2809944  2.09652048 9.61652325 0.84495266
  2.74858244 4.98132828 0.80213543 9.62291072]
 [8.32966048 7.49425465 5.65926957 0.34322203 2.36203174 8.03202473
  0.40901805 9.52794832 3.25481344 2.00717556]
 [7.01496487 7.41792508 0.27893045 9.17667291 2.45372767 1.94723446
  2.35030981 7.86112453 9.97140103 9.53032446]
 [8.67843761 0.24553596 6.78545874 4.89907832 8.56472921 4.21592433
  1.89504399 6.9469186  7.57659015 9.03651456]
 [3.12767021 1.44534442 6.1261859  0.74812356 7.09238526 6.04836563
  7.62190426 1.62412546 0.08232744 7.76873787]
 [5.29612709 4.93549117 3.87553619 8.89962836 8.62326625 6.4942054
  7.34838624 7.33680395 8.2137679  8.55528172]
 [9.96592746 7.91443377 8.19802934 3.64996691 2.01378118 9.63891378
  2.22177775 2.92740461 7.56800694 3.83449645]
 [2.49322023 9.11556188 5.81314203 8.35583925 7.25149796 4.44113556
  8.22642174 3.93385842 4.13261111 9.65623296]
 [9.82226651 2.3161969  2.44767517 1.11209006 1.77606061 5.23124498
  9.8566261  

To transpose this array is quite simple, numpy supplies a `.T` property:

In [3]:
print (nums.T)

[[6.43025026 8.32966048 7.01496487 8.67843761 3.12767021 5.29612709
  9.96592746 2.49322023 9.82226651 2.21383137 6.12191934 7.9224935 ]
 [2.86475989 7.49425465 7.41792508 0.24553596 1.44534442 4.93549117
  7.91443377 9.11556188 2.3161969  7.2899926  3.22760043 0.16381585]
 [2.2809944  5.65926957 0.27893045 6.78545874 6.1261859  3.87553619
  8.19802934 5.81314203 2.44767517 8.81755472 6.8117407  9.65377819]
 [2.09652048 0.34322203 9.17667291 4.89907832 0.74812356 8.89962836
  3.64996691 8.35583925 1.11209006 7.49512541 7.07431858 6.88554149]
 [9.61652325 2.36203174 2.45372767 8.56472921 7.09238526 8.62326625
  2.01378118 7.25149796 1.77606061 8.8814744  3.15012804 9.86635118]
 [0.84495266 8.03202473 1.94723446 4.21592433 6.04836563 6.4942054
  9.63891378 4.44113556 5.23124498 0.89465254 3.59667709 3.63806825]
 [2.74858244 0.40901805 2.35030981 1.89504399 7.62190426 7.34838624
  2.22177775 8.22642174 9.8566261  9.06813666 0.13044803 2.00285444]
 [4.98132828 9.52794832 7.86112453 6.94691

If we want to reshape the array we can use numpy's `reshape` function. For example if I want to "flatten" this array (note there is also a `flatten` function, but `reshape` is more general), we could do:

In [4]:
np.reshape(nums, (120,))

array([6.43025026, 2.86475989, 2.2809944 , 2.09652048, 9.61652325,
       0.84495266, 2.74858244, 4.98132828, 0.80213543, 9.62291072,
       8.32966048, 7.49425465, 5.65926957, 0.34322203, 2.36203174,
       8.03202473, 0.40901805, 9.52794832, 3.25481344, 2.00717556,
       7.01496487, 7.41792508, 0.27893045, 9.17667291, 2.45372767,
       1.94723446, 2.35030981, 7.86112453, 9.97140103, 9.53032446,
       8.67843761, 0.24553596, 6.78545874, 4.89907832, 8.56472921,
       4.21592433, 1.89504399, 6.9469186 , 7.57659015, 9.03651456,
       3.12767021, 1.44534442, 6.1261859 , 0.74812356, 7.09238526,
       6.04836563, 7.62190426, 1.62412546, 0.08232744, 7.76873787,
       5.29612709, 4.93549117, 3.87553619, 8.89962836, 8.62326625,
       6.4942054 , 7.34838624, 7.33680395, 8.2137679 , 8.55528172,
       9.96592746, 7.91443377, 8.19802934, 3.64996691, 2.01378118,
       9.63891378, 2.22177775, 2.92740461, 7.56800694, 3.83449645,
       2.49322023, 9.11556188, 5.81314203, 8.35583925, 7.25149

This indicates that this should become a 1D array with 120 entries. We could also make this a 4 x 30 array or a 30 x 4 array with something like:

In [6]:
np.reshape(nums, (4,30))

array([[6.43025026, 2.86475989, 2.2809944 , 2.09652048, 9.61652325,
        0.84495266, 2.74858244, 4.98132828, 0.80213543, 9.62291072,
        8.32966048, 7.49425465, 5.65926957, 0.34322203, 2.36203174,
        8.03202473, 0.40901805, 9.52794832, 3.25481344, 2.00717556,
        7.01496487, 7.41792508, 0.27893045, 9.17667291, 2.45372767,
        1.94723446, 2.35030981, 7.86112453, 9.97140103, 9.53032446],
       [8.67843761, 0.24553596, 6.78545874, 4.89907832, 8.56472921,
        4.21592433, 1.89504399, 6.9469186 , 7.57659015, 9.03651456,
        3.12767021, 1.44534442, 6.1261859 , 0.74812356, 7.09238526,
        6.04836563, 7.62190426, 1.62412546, 0.08232744, 7.76873787,
        5.29612709, 4.93549117, 3.87553619, 8.89962836, 8.62326625,
        6.4942054 , 7.34838624, 7.33680395, 8.2137679 , 8.55528172],
       [9.96592746, 7.91443377, 8.19802934, 3.64996691, 2.01378118,
        9.63891378, 2.22177775, 2.92740461, 7.56800694, 3.83449645,
        2.49322023, 9.11556188, 5.81314203, 8.

In [7]:
np.reshape(nums, (30,4))

array([[6.43025026, 2.86475989, 2.2809944 , 2.09652048],
       [9.61652325, 0.84495266, 2.74858244, 4.98132828],
       [0.80213543, 9.62291072, 8.32966048, 7.49425465],
       [5.65926957, 0.34322203, 2.36203174, 8.03202473],
       [0.40901805, 9.52794832, 3.25481344, 2.00717556],
       [7.01496487, 7.41792508, 0.27893045, 9.17667291],
       [2.45372767, 1.94723446, 2.35030981, 7.86112453],
       [9.97140103, 9.53032446, 8.67843761, 0.24553596],
       [6.78545874, 4.89907832, 8.56472921, 4.21592433],
       [1.89504399, 6.9469186 , 7.57659015, 9.03651456],
       [3.12767021, 1.44534442, 6.1261859 , 0.74812356],
       [7.09238526, 6.04836563, 7.62190426, 1.62412546],
       [0.08232744, 7.76873787, 5.29612709, 4.93549117],
       [3.87553619, 8.89962836, 8.62326625, 6.4942054 ],
       [7.34838624, 7.33680395, 8.2137679 , 8.55528172],
       [9.96592746, 7.91443377, 8.19802934, 3.64996691],
       [2.01378118, 9.63891378, 2.22177775, 2.92740461],
       [7.56800694, 3.83449645,

In all cases the order of the data is preserved. There is a bit more information on reshaping an array here:

https://www.w3resource.com/numpy/manipulation/reshape.php

If you try to do something invalid, the code will fail:

In [8]:
np.reshape(nums, (30,10))

ValueError: cannot reshape array of size 120 into shape (30,10)

## EXERCISE

Create a 2D array (x,y) whose values should be equal to $x**2 + y$ (so the value at `[0,1]` would be 1, the value at `[2,4]` would be $2^2 + 4 = 8$ and so on). The size of this array should be 42 x 20.

Take the transpose of this array. Now if this new array has coordinates (x1,y1) what is the value at x1 = 4, y1=5 going to be?

There are a number of different 2D shapes that you can reshape this array into (I counted 32). How many valid different sizes can you reshape this array into.

Reshape this array into a 5D shape, where no dimension has a size equal to 1.

## Matrix operations

A 2D array in numpy can be treated as a matrix, but unlike in MATLAB, it will *not* be treated mathematically as a matrix unless you tell it. For example doing `a * b` will perform elementwise multiplication, not matrix multiplication. BUT, we can still do all matrix stuff in MATLAB in numpy just as easily.

First let's show elementwise multiplication:

In [11]:
nums1 = np.random.random_sample(size=[12,10]) * 10
nums2 = np.random.random_sample(size=[12,10]) * 10
nums3 = np.random.random_sample(size=[10,10]) * 10

prod = nums1 * nums2
# To multiply two numpy arrays they must be the same shape, and then every element is multiplied by its corresponding
# element in the other array. That's not how matrix multiplication works
print (prod.shape)
print()

# This won't work, they are not the same shape!
prod2 = nums1 * nums3


(12, 10)



ValueError: operands could not be broadcast together with shapes (12,10) (10,10) 

Now let's show matrix multiplication, we use the `@` operator to do this:

In [17]:
# The @ indicates matrix multiplication, nums1 can be multiplied by nums3
mult1 = nums1 @ nums3

print(mult1)

# But nums1 cannot be multiplied by nums2.
# I cannot multiply a 12x10 matrix by a 12x10 matrix!
# Let's catch this error and continue. Python's try/except can be used for this
# https://docs.python.org/3/tutorial/errors.html

try:
    nums1 @ nums2
except ValueError as err:
    print ("This doesn't work! The [not particularly helpful] error message says:")
    print (err)

# But I can multiply a 12x10 matrix by a 10x12 matrix (the resulting matrix should be 12 x 12.)
# OR I can multiply a 10x12 matrix by a 12x10 matrix (resulting in a 10x10 matrix)

prod1 = nums1 @ nums2.T
prod2 = nums1.T @ nums2

print (prod1.shape, prod2.shape)

[[289.67344461 298.05167723 367.98827803 243.16407347 218.09777033
  240.48217323 230.83158971 361.47921509 336.39241281 211.84751252]
 [408.20116333 363.34921745 441.69740825 321.29239865 328.37912117
  298.40486436 297.59803813 440.75293428 349.98495504 262.39601721]
 [227.21133078 219.54689441 240.46028394 140.99283956 162.82616874
  175.39878348 209.96927847 217.78353406 198.86884926 164.12995408]
 [274.97153204 315.44378009 302.74106642 230.94157383 251.97642205
  276.01650607 251.62202724 336.01612377 350.41932782 245.53329838]
 [366.9625905  300.8956934  332.08657045 284.12207392 215.34880723
  286.69768369 310.80223219 344.88422052 285.18057649 266.76324368]
 [283.055845   290.14382198 341.15746639 231.95266924 221.86511777
  270.59325167 194.20916346 363.32798872 370.25660805 214.11405292]
 [419.19654968 350.72701219 436.90233706 339.11124797 227.27295798
  365.78807043 360.17331483 457.94288721 409.94738778 350.20163558]
 [324.2978075  276.19084495 330.53990059 229.9434306  2

We can also compute the eigenvalues and eigenvectors of a square 2D array :

In [18]:
# Make a diagonal matrix
nums1 = np.zeros([3,3])
nums1[0,0] = 1.
nums1[1,1] = 2.
nums1[2,2] = 3.
print(nums1)
# Or equivalently
print (np.diag([1.,2.,3.]))

evals, evecs = np.linalg.eig(nums1)

print (evals)
print (evecs)

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## EXERCISE

Generate a 2D 10x10 matrix of random numbers. Compute the eigenvectors and eigenvalues of this matrix.

Now try again but this time generate a symmetric matrix (where the value at `[x,y]` is equal to the value at `[y,x]`). What do you notice is different? Why is this?